Repository 42-Tomodachi/ft_transcendence, pull requests merged in 2022-06, with the labels that each got.

#11 [FE] FEATURE: Context API 설정
  frontend/.gitignore
  frontend/db.json
  frontend/src/App.tsx
  frontend/src/components/common/Button.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/OauthPage.tsx
  frontend/src/store/index.tsx
  frontend/src/utils/interface.ts
Labels: FE

#34 [FE] make Header, HomPage, Modal, RoomList template
  frontend/.gitignore
  frontend/db.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/assets/close.png
  frontend/src/assets/logo-white.png
  frontend/src/components/Chat/index.tsx
  frontend/src/components/Game/LadderModal.tsx
  frontend/src/components/Game/RoomList.tsx
  frontend/src/components/Game/RoomListItem.tsx
  frontend/src/components/Game/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/common/Modal/LogoutModal.tsx
  frontend/src/components/common/Modal/ModalSet.tsx
  frontend/src/components/common/Modal/index.tsx
  frontend/src/pages/GamePage.tsx
  frontend/src/pages/HomePage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/OauthPage.tsx
  frontend/src/store/index.tsx
  frontend/src/utils/interface.ts
Labels: FE

#20 [Fe #17] make user profile
  frontend/.gitignore
  frontend/db.json
  frontend/src/App.tsx
  frontend/src/components/UserProfile/index.tsx
  frontend/yarn.lock
Labels: enhancement, FE

#44 [Fe #41] ShowProfile(Modal) UI 제작
  frontend/db.json
  frontend/src/App.tsx
  frontend/src/components/common/Modal/ModalSet.tsx
  frontend/src/components/common/Modal/ModalTester.tsx
  frontend/src/components/common/Modal/ShowProfile.tsx
Labels: enhancement, FE

#43 [FE] ChatRoom 페이지 제작
  frontend/db.json
  frontend/src/App.tsx
  frontend/src/components/Chat/ChatRoom.tsx
  frontend/src/components/Chat/MessageInput.tsx
  frontend/src/components/Chat/MessageItem.tsx
  frontend/src/components/Chat/MessageList.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/utils/interface.ts
Labels: FE

#13 [FE] TEST: 2차인증창 & 유저리스트창
  frontend/db.json
  frontend/src/App.tsx
  frontend/src/components/UserList/index.tsx
  frontend/src/pages/SecondAuthPage.tsx
  frontend/src/utils/interface.ts
Labels: FE

#25 [FE] make nickname page
  frontend/db.json
  frontend/src/pages/NicknamPage.tsx
Labels: FE

#57 [FE] 프론트 자잘한 수정
  frontend/db.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/assets/default-image.png
  frontend/src/components/Chat/MessageItem.tsx
  frontend/src/components/Chat/index.tsx
  frontend/src/components/Game/index.tsx
  frontend/src/components/RoomList/RoomListItem.tsx
  frontend/src/components/RoomList/index.tsx
  frontend/src/components/UserList/UserItem.tsx
  frontend/src/components/UserList/index.tsx
  frontend/src/components/UserProfile/index.tsx
  frontend/src/components/common/Button.tsx
  frontend/src/components/common/Modal/ShowProfile.tsx
  frontend/src/components/common/Modal/index.tsx
  frontend/src/components/common/ProfileImage.tsx
  frontend/src/pages/HomePage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/NicknamePage.tsx
  frontend/src/pages/SecondAuthPage.tsx
  frontend/src/utils/interface.ts
Labels: FE

#64 Be #26 kankim
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/auth.dto.ts
  backend/src/chat/chat.controller.ts
  backend/src/chat/chat.service.ts
  backend/src/chat/entities/chatContents.entity.ts
  backend/src/chat/entities/chatParticipant.entity.ts
  backend/src/chat/entities/chattingRoom.entity.ts
  backend/src/gameRecord/entities/gameRecord.entity.ts
  backend/src/users/dto/users.dto.ts
  backend/src/users/entities/blockedUser.entity.ts
  backend/src/users/entities/follow.entity.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
Labels: BE

#71 Be #26 kankim
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/auth.dto.ts
  backend/src/chat/entities/chattingRoom.entity.ts
  backend/src/gameRecord/gameRecord.controller.spec.ts
  backend/src/gameRecord/gameRecord.controller.ts
  backend/src/gameRecord/gameRecord.module.ts
  backend/src/gameRecord/gameRecord.service.spec.ts
  backend/src/gameRecord/gameRecord.service.ts
  backend/src/users/dto/gameRecord.dto.ts
  backend/src/users/dto/users.dto.ts
  backend/src/users/entities/blockedUser.entity.ts
  backend/src/users/entities/follow.entity.ts
  backend/src/users/entities/gameRecord.entity.ts
  backend/src/users/entities/users.entity.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.module.ts
  backend/src/users/users.service.ts
Labels: BE

#72 [BE] FEAT: uploadImage 추가.
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/auth.dto.ts
  backend/src/files/default_profile.png
  backend/src/files/file-uploading.utils.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
Labels: BE

#68 [FE] add dockerfile, docker compose
  docker-compose.yml
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/ENTRYPOINT.sh
  frontend/src/pages/NicknamePage.tsx
Labels: FE

#75 [BE] 닉네임 변경 api 구현
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
Labels: BE

#69 [FE] 디자인 및 파일명 수정
  frontend/src/App.tsx
  frontend/src/components/Chat/ChatRoom.tsx
  frontend/src/components/Chat/index.tsx
  frontend/src/components/Game/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/RoomList/RoomListItem.tsx
  frontend/src/components/RoomList/index.tsx
  frontend/src/components/common/Modal/LogoutModal.tsx
  frontend/src/pages/ChatPage.tsx
  frontend/src/pages/HomePage.tsx
  frontend/src/utils/interface.ts
Labels: FE

#77 [BE] 채팅방참여자목록, signUp에서 id전달, 리팩토링
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/auth.dto.ts
  backend/src/chat/chat.controller.ts
  backend/src/chat/chat.module.ts
  backend/src/chat/chat.service.ts
  backend/src/chat/dto/chat.dto.ts
  backend/src/chat/entities/chatContents.entity.ts
  backend/src/chat/entities/chatParticipant.entity.ts
  backend/src/chat/entities/chattingRoom.entity.ts
  backend/src/users/dto/users.dto.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
Labels: BE

#79 Be #26 enter chatting room
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/chat/chat.controller.ts
  backend/src/chat/chat.service.ts
  backend/src/chat/dto/chat.dto.ts
  backend/src/chat/entities/chattingRoom.entity.ts
  backend/src/users/dto/follow.dto.ts
  backend/src/users/dto/users.dto.ts
  backend/src/users/entities/users.entity.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
Labels: BE

#80 [BE] FEAT: 채팅방 나가기 api 구현
  backend/src/chat/chat.controller.ts
  backend/src/chat/chat.service.ts
  backend/src/chat/entities/chatContents.entity.ts
  backend/src/chat/entities/chatParticipant.entity.ts
Labels: BE
